name: Update 3D Models JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at noon UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Generate models.json
      run: |
        echo '[
          {
            "title": "Link Master Sword",
            "image": "https://example.com/images/linksword.jpg",
            "tags": ["Zelda", "Gaming", "Weapon"],
            "link": "https://cults3d.com/en/models/links-master-sword"
          },
          {
            "title": "Pikachu Figurine",
            "image": "https://example.com/images/pikachu.jpg",
            "tags": ["Pokemon", "Anime", "Miniature"],
            "link": "https://cults3d.com/en/models/pikachu-figurine"
          }
        ]' > models.json

    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@users.noreply.github.com
        git add models.json
        git commit -m "Auto-update models.json"
        git push