name: Update Models

on:
  workflow_dispatch: # allow manual runs
  schedule:
    - cron: '0 12 * * 1' # every Monday at noon UTC
  push: # run automatically when you update these files
    paths:
      - 'fetch_cults_models.py'
      - '.github/workflows/update-models.yml'

permissions:
  contents: write

jobs:
  fetch-cults-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Cults3D fetch script
        env:
          CULTS_API_KEY: ${{ secrets.CULTS_API_KEY }}
        run: |
          python fetch_cults_models.py

      - name: Commit and push models.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add models.json
          git diff --cached --quiet || git commit -m "Auto-update models.json from Cults3D"
          git push
